import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        gold: "hsl(var(--gold))",
        blue: "hsl(var(--blue))",
        emerald: "hsl(var(--emerald))",
        violet: "hsl(var(--violet))",
        pink: "hsl(var(--pink))",
        orange: "hsl(var(--orange))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        display: ['"Cormorant Garamond"', 'Georgia', 'serif'],
        body: ['"DM Sans"', 'system-ui', 'sans-serif'],
        arabic: ['Amiri', '"Cormorant Garamond"', 'serif'],
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-gold': 'var(--gradient-gold)',
        'gradient-gold-soft': 'var(--gradient-gold-soft)',
        'gradient-blue': 'var(--gradient-blue)',
        'gradient-emerald': 'var(--gradient-emerald)',
        'gradient-mixed': 'var(--gradient-mixed)',
      },
      boxShadow: {
        gold: 'var(--shadow-gold)',
        blue: 'var(--shadow-blue)',
        glass: 'var(--shadow-glass)',
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-up": { "0%": { opacity: "0", transform: "translateY(18px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-in": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "slide-right": { "0%": { opacity: "0", transform: "translateX(20px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        "spring-in": { "0%": { opacity: "0", transform: "scale(0.85)" }, "60%": { opacity: "1", transform: "scale(1.02)" }, "100%": { transform: "scale(1)" } },
        "float-y": { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-12px)" } },
        "mesh-drift": { "0%,100%": { transform: "translate3d(0,0,0) scale(1)" }, "50%": { transform: "translate3d(5%,-4%,0) scale(1.08)" } },
        "pulse-dot": { "0%,100%": { boxShadow: "0 0 0 0 hsl(var(--emerald) / 0.7)" }, "50%": { boxShadow: "0 0 0 8px hsl(var(--emerald) / 0)" } },
        "bounce-dot": { "0%,80%,100%": { transform: "translateY(0)", opacity: "0.4" }, "40%": { transform: "translateY(-6px)", opacity: "1" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-up": "fade-up 0.7s cubic-bezier(0.22,1,0.36,1) both",
        "fade-in": "fade-in 0.5s ease-out both",
        "slide-right": "slide-right 0.4s cubic-bezier(0.22,1,0.36,1) both",
        "spring-in": "spring-in 0.5s cubic-bezier(0.34,1.56,0.64,1) both",
        "float-y": "float-y 6s ease-in-out infinite",
        "mesh-drift": "mesh-drift 22s ease-in-out infinite",
        "pulse-dot": "pulse-dot 2s ease-in-out infinite",
        "bounce-dot": "bounce-dot 1.2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
